services:
  database:
    image: mariadb
    container_name: final-mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: 3rd
      MARIADB_PASSWORD: 1234
      MARIADB_DATABASE: team3
    volumes:
      - ./src/main/resources/db_config/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3000:3306

  app:
    container_name: agepred
    build: .
    ports:
      - 3003:8972
    restart: always
    depends_on:
      - database
    links:
      - database
    platform: linux/amd64
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://database:3306/team3
